/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as ReviewSessionIdRouteImport } from './routes/review.$sessionId'
import { Route as FocusSessionIdRouteImport } from './routes/focus.$sessionId'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppGroupsRouteImport } from './routes/_app.groups'
import { Route as AppFriendsRouteImport } from './routes/_app.friends'
import { Route as AppCommunityRouteImport } from './routes/_app.community'
import { Route as AppAppRouteImport } from './routes/_app.app'
import { Route as AppSubjectSubjectIdRouteImport } from './routes/_app.subject.$subjectId'
import { Route as AppGroupGroupIdRouteImport } from './routes/_app.group.$groupId'
import { Route as AppDmFriendIdRouteImport } from './routes/_app.dm.$friendId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewSessionIdRoute = ReviewSessionIdRouteImport.update({
  id: '/review/$sessionId',
  path: '/review/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusSessionIdRoute = FocusSessionIdRouteImport.update({
  id: '/focus/$sessionId',
  path: '/focus/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectSubjectIdRoute = AppSubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupGroupIdRoute = AppGroupGroupIdRouteImport.update({
  id: '/group/$groupId',
  path: '/group/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppDmFriendIdRoute = AppDmFriendIdRouteImport.update({
  id: '/dm/$friendId',
  path: '/dm/$friendId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/app': typeof AppAppRoute
  '/community': typeof AppCommunityRoute
  '/friends': typeof AppFriendsRoute
  '/groups': typeof AppGroupsRoute
  '/history': typeof AppHistoryRoute
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/focus/$sessionId': typeof FocusSessionIdRoute
  '/review/$sessionId': typeof ReviewSessionIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/dm/$friendId': typeof AppDmFriendIdRoute
  '/group/$groupId': typeof AppGroupGroupIdRoute
  '/subject/$subjectId': typeof AppSubjectSubjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/app': typeof AppAppRoute
  '/community': typeof AppCommunityRoute
  '/friends': typeof AppFriendsRoute
  '/groups': typeof AppGroupsRoute
  '/history': typeof AppHistoryRoute
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/focus/$sessionId': typeof FocusSessionIdRoute
  '/review/$sessionId': typeof ReviewSessionIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/dm/$friendId': typeof AppDmFriendIdRoute
  '/group/$groupId': typeof AppGroupGroupIdRoute
  '/subject/$subjectId': typeof AppSubjectSubjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/_app/app': typeof AppAppRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/friends': typeof AppFriendsRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/rooms': typeof AppRoomsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/focus/$sessionId': typeof FocusSessionIdRoute
  '/review/$sessionId': typeof ReviewSessionIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/_app/dm/$friendId': typeof AppDmFriendIdRoute
  '/_app/group/$groupId': typeof AppGroupGroupIdRoute
  '/_app/subject/$subjectId': typeof AppSubjectSubjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/login'
    | '/app'
    | '/community'
    | '/friends'
    | '/groups'
    | '/history'
    | '/rooms'
    | '/settings'
    | '/tasks'
    | '/focus/$sessionId'
    | '/review/$sessionId'
    | '/room/$roomId'
    | '/dm/$friendId'
    | '/group/$groupId'
    | '/subject/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/login'
    | '/app'
    | '/community'
    | '/friends'
    | '/groups'
    | '/history'
    | '/rooms'
    | '/settings'
    | '/tasks'
    | '/focus/$sessionId'
    | '/review/$sessionId'
    | '/room/$roomId'
    | '/dm/$friendId'
    | '/group/$groupId'
    | '/subject/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/leaderboard'
    | '/login'
    | '/_app/app'
    | '/_app/community'
    | '/_app/friends'
    | '/_app/groups'
    | '/_app/history'
    | '/_app/rooms'
    | '/_app/settings'
    | '/_app/tasks'
    | '/focus/$sessionId'
    | '/review/$sessionId'
    | '/room/$roomId'
    | '/_app/dm/$friendId'
    | '/_app/group/$groupId'
    | '/_app/subject/$subjectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  FocusSessionIdRoute: typeof FocusSessionIdRoute
  ReviewSessionIdRoute: typeof ReviewSessionIdRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$sessionId': {
      id: '/review/$sessionId'
      path: '/review/$sessionId'
      fullPath: '/review/$sessionId'
      preLoaderRoute: typeof ReviewSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus/$sessionId': {
      id: '/focus/$sessionId'
      path: '/focus/$sessionId'
      fullPath: '/focus/$sessionId'
      preLoaderRoute: typeof FocusSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subject/$subjectId': {
      id: '/_app/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof AppSubjectSubjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/group/$groupId': {
      id: '/_app/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof AppGroupGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dm/$friendId': {
      id: '/_app/dm/$friendId'
      path: '/dm/$friendId'
      fullPath: '/dm/$friendId'
      preLoaderRoute: typeof AppDmFriendIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppDmFriendIdRoute: typeof AppDmFriendIdRoute
  AppGroupGroupIdRoute: typeof AppGroupGroupIdRoute
  AppSubjectSubjectIdRoute: typeof AppSubjectSubjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppDmFriendIdRoute: AppDmFriendIdRoute,
  AppGroupGroupIdRoute: AppGroupGroupIdRoute,
  AppSubjectSubjectIdRoute: AppSubjectSubjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  FocusSessionIdRoute: FocusSessionIdRoute,
  ReviewSessionIdRoute: ReviewSessionIdRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
